start = expression

quote = 
 "'" a:expression {return  ['quote'].concat([a]);}




validchar
    = [0-9a-zA-Z_?!+\-=@#$%^&*/.]

atom =
    chars:validchar+
        { return chars.join(""); }


space = 
 " "*

newline = 
 "\n"*

spacenewline = 
  (" " / "\n")*

sea = 
   atom
/  s

seaspace =
   spacenewline a:sea spacenewline {return a;}

sel = 
   seaspace+

s = 
  "(" a:sel ")" {return a;}

expression = 
  atom
/ s
/ quote



